# This file defines the different types of taxonomies in Bolt. See the
# documentation for details: https://docs.bolt.cm/contenttypes/taxonomies

groups:
    slug: groups
    singular_slug: group
    behaves_like: grouping
    options: { main: "The main group", meta: "Meta group", other: "The other stuff" }
    has_sortorder: true
    required: false

categorias:
    name: Categorias
    slug: categorias
    singular_name: Categoria
    singular_slug: categoria
    behaves_like: categories
    multiple: false
    listing_template: products_by_category.twig
    options: [ "Hardware e periféricos de computador", "Alimentos" ]
    required: false

tags:
    slug: tags
    singular_slug: tag
    behaves_like: tags
    postfix: "Adicione algumas tags de forma livre. Inicie uma nova tag digitando uma vírgula ou espaço."
    allow_spaces: false
    listing_template: products_by_category.twig
    required: false